import 'dart:io';

import 'package:mobile/core/backend/repositories/post_repository.dart';
import 'package:mobile/core/backend/supabase_client.dart';
import 'package:mobile/core/models/comment.dart';
import 'package:mobile/core/models/post.dart';
import 'package:mobile/core/utils/backend_error.dart';
import 'package:mobile/core/utils/logger.dart';
import 'package:mobile/core/utils/result.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

/// Supabase implementation of [PostRepository].
///
/// All primary keys (posts.id, comments.id) are generated by PostgreSQL
/// via `gen_random_uuid()`. The client never sends an `id` column on
/// insert; instead it uses `.select().single()` to retrieve the
/// database-generated UUID and returns it to the caller.
class PostRepositoryImpl implements PostRepository {
  // ──────────────────────────────────────────────────────────────
  // Posts
  // ──────────────────────────────────────────────────────────────

  /// Loads all posts from Supabase with joined author profile data.
  /// Returns newest posts first.
  ///
  /// Populates `likes_count`, `comments_count`, and `likedBy` from the
  /// database so the feed reflects server-confirmed state.
  @override
  Future<Result<List<Post>>> loadPosts(String userId) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.failure(const Failure('ORA backend is not configured.'));
    }

    try {
      final client = SupabaseClientProvider.client!;

      final response = await client
          .from('posts')
          .select('''
             *,
             profiles!posts_user_id_fkey (
               user_id,
               username,
               display_name,
               avatar,
               aura_points
             ),
             post_likes!left (
               user_id
             )
           ''')
          .order('created_at', ascending: false);

      final posts = response.map((row) {
        final profile = row['profiles'] as Map<String, dynamic>?;
        final likes = row['post_likes'] as List<dynamic>? ?? [];

        // Build the set of user IDs who liked this post.
        final likedBy = likes
            .map((like) => (like as Map<String, dynamic>)['user_id'] as String)
            .toSet();

        return Post(
          id: row['id'] as String,
          userId: row['user_id'] as String,
          username: profile?['username'] as String? ?? 'user',
          displayName: profile?['display_name'] as String?,
          avatarUrl: profile?['avatar'] as String?,
          content: row['content'] as String? ?? '',
          mediaUrls: row['media_urls'] != null
              ? List<String>.from(row['media_urls'] as List)
              : <String>[],
          likes: row['likes_count'] as int? ?? likedBy.length,
          comments: row['comments_count'] as int? ?? 0,
          shares: row['shares_count'] as int? ?? 0,
          likedBy: likedBy,
          createdAt:
              DateTime.tryParse(row['created_at'] as String? ?? '') ??
              DateTime.now(),
          updatedAt: row['updated_at'] != null
              ? DateTime.tryParse(row['updated_at'] as String? ?? '')
              : null,
        );
      }).toList();

      return Result.success(posts);
    } catch (e, stack) {
      _logError('loadPosts', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  /// Loads a single post by ID with joined author profile data.
  @override
  Future<Result<Post?>> getPost(String postId, String userId) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.success(null);
    }

    try {
      final client = SupabaseClientProvider.client!;

      final response = await client
          .from('posts')
          .select('''
             *,
             profiles!posts_user_id_fkey (
               user_id,
               username,
               display_name,
               avatar,
               aura_points
             ),
             post_likes!left (
               user_id
             )
           ''')
          .eq('id', postId)
          .maybeSingle();

      if (response == null) {
        return Result.success(null);
      }

      final profile = response['profiles'] as Map<String, dynamic>?;
      final likes = response['post_likes'] as List<dynamic>? ?? [];

      final likedBy = likes
          .map((like) => (like as Map<String, dynamic>)['user_id'] as String)
          .toSet();

      final post = Post(
        id: response['id'] as String,
        userId: response['user_id'] as String,
        username: profile?['username'] as String? ?? 'user',
        displayName: profile?['display_name'] as String?,
        avatarUrl: profile?['avatar'] as String?,
        content: response['content'] as String? ?? '',
        mediaUrls: response['media_urls'] != null
            ? List<String>.from(response['media_urls'] as List)
            : <String>[],
        likes: response['likes_count'] as int? ?? likedBy.length,
        comments: response['comments_count'] as int? ?? 0,
        shares: response['shares_count'] as int? ?? 0,
        likedBy: likedBy,
        createdAt:
            DateTime.tryParse(response['created_at'] as String? ?? '') ??
            DateTime.now(),
        updatedAt: response['updated_at'] != null
            ? DateTime.tryParse(response['updated_at'] as String? ?? '')
            : null,
      );

      return Result.success(post);
    } catch (e, stack) {
      _logError('getPost', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  /// Creates a new post in Supabase.
  ///
  /// The `id` column is never sent — PostgreSQL generates it via
  /// `gen_random_uuid()`. The database-generated row is returned via
  /// `.select().single()` and the persisted UUID is used in the
  /// returned [Post].
  @override
  Future<Result<Post>> createPost(Post post) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.failure(const Failure('Supabase not initialized'));
    }

    try {
      final client = SupabaseClientProvider.client!;

      final response = await client
          .from('posts')
          .insert({
            'user_id': post.userId,
            'content': post.content,
            'media_urls': post.mediaUrls,
            'likes_count': post.likes,
            'comments_count': post.comments,
            'shares_count': post.shares,
            'created_at': post.createdAt.toIso8601String(),
            'updated_at': post.updatedAt?.toIso8601String(),
          })
          .select('''
        *,
        profiles!posts_user_id_fkey (
          user_id,
          username,
          display_name,
          avatar,
          aura_points
        )
      ''')
          .single();

      return Result.success(_mapPostFromRow(response, post));
    } catch (e, stack) {
      _logError('createPost', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  /// Updates an existing post in Supabase.
  @override
  Future<Result<Post>> updatePost(Post post) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.failure(const Failure('Supabase not initialized'));
    }

    try {
      final client = SupabaseClientProvider.client!;

      final response = await client
          .from('posts')
          .update({
            'content': post.content,
            'media_urls': post.mediaUrls,
            'updated_at': DateTime.now().toIso8601String(),
          })
          .eq('id', post.id)
          .select('''
        *,
        profiles!posts_user_id_fkey (
          user_id,
          username,
          display_name,
          avatar,
          aura_points
        )
      ''')
          .single();

      return Result.success(_mapPostFromRow(response, post));
    } catch (e, stack) {
      _logError('updatePost', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  /// Deletes a post from Supabase.
  @override
  Future<Result<void>> deletePost(String postId) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.failure(const Failure('Supabase not initialized'));
    }

    try {
      final client = SupabaseClientProvider.client!;
      await client.from('posts').delete().eq('id', postId);
      return Result.success(null);
    } catch (e, stack) {
      _logError('deletePost', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  // ──────────────────────────────────────────────────────────────
  // Post Likes
  // ──────────────────────────────────────────────────────────────

  /// Toggles a like on a post in the `post_likes` table.
  ///
  /// The `post_likes` table uses `gen_random_uuid()` for its own primary
  /// key, so no `id` is sent on insert. Only `post_id` and `user_id` are
  /// supplied.
  @override
  Future<Result<LikeToggleResult>> toggleLike(
    String postId,
    String userId,
  ) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.failure(const Failure('Supabase not initialized'));
    }

    try {
      final client = SupabaseClientProvider.client!;

      final existingLike = await client
          .from('post_likes')
          .select()
          .eq('post_id', postId)
          .eq('user_id', userId)
          .maybeSingle();

      if (existingLike != null) {
        await client
            .from('post_likes')
            .delete()
            .eq('post_id', postId)
            .eq('user_id', userId);

        // Decrement the post's likes_count atomically.
        await client.rpc('decrement_post_likes', params: {'post_id': postId});

        return Result.success(const LikeToggleResult(isLiked: false, likes: 0));
      }

      await client.from('post_likes').insert({
        'post_id': postId,
        'user_id': userId,
      });

      // Increment the post's likes_count atomically.
      await client.rpc('increment_post_likes', params: {'post_id': postId});

      return Result.success(const LikeToggleResult(isLiked: true, likes: 1));
    } catch (e, stack) {
      _logError('toggleLike', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  /// Legacy like method — delegates to [toggleLike].
  @override
  Future<Result<void>> likePost(String postId, String userId) async {
    await toggleLike(postId, userId);
    return Result.success(null);
  }

  /// Legacy unlike method — delegates to [toggleLike].
  @override
  Future<Result<void>> unlikePost(String postId, String userId) async {
    await toggleLike(postId, userId);
    return Result.success(null);
  }

  // ──────────────────────────────────────────────────────────────
  // Comments
  // ──────────────────────────────────────────────────────────────

  /// Creates a new comment in the `comments` table.
  ///
  /// The `id` column is never sent — PostgreSQL generates it via
  /// `gen_random_uuid()`. The database-generated row is returned via
  /// `.select().single()` and the persisted UUID is used in the
  /// returned [Comment].
  @override
  Future<Result<Comment>> createComment(Comment comment) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.failure(const Failure('Supabase not initialized'));
    }

    try {
      final client = SupabaseClientProvider.client!;

      final response = await client
          .from('comments')
          .insert({
            'post_id': comment.postId,
            'user_id': comment.userId,
            'parent_id': comment.parentId,
            'content': comment.content,
            'is_edited': comment.isEdited,
            'is_deleted': comment.isDeleted,
            'created_at': comment.createdAt.toIso8601String(),
            'updated_at': comment.updatedAt?.toIso8601String(),
          })
          .select('''
        *,
        profiles!comments_user_id_fkey (
          user_id,
          username,
          display_name,
          avatar
        )
      ''')
          .single();

      // Increment the post's comments_count atomically.
      await client.rpc(
        'increment_post_comments',
        params: {'post_id': comment.postId},
      );

      return Result.success(_mapCommentFromRow(response, comment));
    } catch (e, stack) {
      _logError('createComment', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  /// Edits an existing comment in Supabase.
  @override
  Future<Result<Comment>> editComment(Comment comment) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.failure(const Failure('Supabase not initialized'));
    }

    try {
      final client = SupabaseClientProvider.client!;

      final response = await client
          .from('comments')
          .update({
            'content': comment.content,
            'is_edited': true,
            'updated_at': DateTime.now().toIso8601String(),
          })
          .eq('id', comment.id)
          .select('''
        *,
        profiles!comments_user_id_fkey (
          user_id,
          username,
          display_name,
          avatar
        )
      ''')
          .single();

      return Result.success(_mapCommentFromRow(response, comment));
    } catch (e, stack) {
      _logError('editComment', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  /// Soft-deletes a comment in Supabase and decrements the post's
  /// comment count via an RPC.
  @override
  Future<Result<void>> deleteComment(String commentId) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.failure(const Failure('Supabase not initialized'));
    }

    try {
      final client = SupabaseClientProvider.client!;

      final row = await client
          .from('comments')
          .select('post_id')
          .eq('id', commentId)
          .single();

      await client
          .from('comments')
          .update({
            'is_deleted': true,
            'updated_at': DateTime.now().toIso8601String(),
          })
          .eq('id', commentId);

      final postId = row['post_id'] as String;
      await client.rpc('decrement_post_comments', params: {'post_id': postId});

      return Result.success(null);
    } catch (e, stack) {
      _logError('deleteComment', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  /// Loads all non-deleted comments for a post, ordered newest first.
  @override
  Future<Result<List<Comment>>> getComments(String postId) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.success(<Comment>[]);
    }

    try {
      final client = SupabaseClientProvider.client!;

      final response = await client
          .from('comments')
          .select('''
            *,
            profiles!comments_user_id_fkey (
              user_id,
              username,
              display_name,
              avatar
            )
          ''')
          .eq('post_id', postId)
          .eq('is_deleted', false)
          .order('created_at', ascending: false);

      final comments = response.map((row) {
        return _mapCommentFromRow(row, null);
      }).toList();

      return Result.success(comments);
    } catch (e, stack) {
      _logError('getComments', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  // ──────────────────────────────────────────────────────────────
  // Bookmarks
  // ──────────────────────────────────────────────────────────────

  /// Checks if a post is bookmarked by a user.
  @override
  Future<Result<bool>> isBookmarked(String postId, String userId) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.success(false);
    }

    try {
      final client = SupabaseClientProvider.client!;

      final response = await client
          .from('bookmarks')
          .select('id')
          .eq('user_id', userId)
          .eq('post_id', postId)
          .maybeSingle();

      return Result.success(response != null);
    } catch (e, stack) {
      _logError('isBookmarked', e, stack);
      return Result.success(false);
    }
  }

  /// Bookmarks a post for a user.
  @override
  Future<Result<void>> bookmarkPost(String postId, String userId) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.success(null);
    }

    try {
      final client = SupabaseClientProvider.client!;

      await client.from('bookmarks').insert({
        'user_id': userId,
        'post_id': postId,
      });

      return Result.success(null);
    } catch (e, stack) {
      _logError('bookmarkPost', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  /// Removes a bookmark from a post for a user.
  @override
  Future<Result<void>> removeBookmark(String postId, String userId) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.success(null);
    }

    try {
      final client = SupabaseClientProvider.client!;

      await client
          .from('bookmarks')
          .delete()
          .eq('user_id', userId)
          .eq('post_id', postId);

      return Result.success(null);
    } catch (e, stack) {
      _logError('removeBookmark', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  /// Loads all bookmarked posts for a user.
  @override
  Future<Result<List<Post>>> loadBookmarks(String userId) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.success(<Post>[]);
    }

    try {
      final client = SupabaseClientProvider.client!;

      final response = await client
          .from('bookmarks')
          .select('''
            post_id,
            posts!inner (
              *,
              profiles!posts_user_id_fkey (
                user_id,
                username,
                display_name,
                avatar,
                aura_points
              )
            )
          ''')
          .eq('user_id', userId)
          .order('created_at', ascending: false);

      final posts = response.map((row) {
        final post = row['posts'] as Map<String, dynamic>;
        final profile = post['profiles'] as Map<String, dynamic>?;

        return Post(
          id: post['id'] as String,
          userId: post['user_id'] as String,
          username: profile?['username'] as String? ?? 'user',
          displayName: profile?['display_name'] as String?,
          avatarUrl: profile?['avatar'] as String?,
          content: post['content'] as String? ?? '',
          mediaUrls: post['media_urls'] != null
              ? List<String>.from(post['media_urls'] as List)
              : <String>[],
          likes: post['likes_count'] as int? ?? 0,
          comments: post['comments_count'] as int? ?? 0,
          shares: post['shares_count'] as int? ?? 0,
          createdAt:
              DateTime.tryParse(post['created_at'] as String? ?? '') ??
              DateTime.now(),
          updatedAt: post['updated_at'] != null
              ? DateTime.tryParse(post['updated_at'] as String? ?? '')
              : null,
        );
      }).toList();

      return Result.success(posts);
    } catch (e, stack) {
      _logError('loadBookmarks', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  // ──────────────────────────────────────────────────────────────
  // Comment Likes
  // ──────────────────────────────────────────────────────────────

  /// Toggles a like on a comment in the `comment_likes` table.
  ///
  /// The `comment_likes` table uses `gen_random_uuid()` for its own
  /// primary key, so no `id` is sent on insert.
  @override
  Future<Result<LikeToggleResult>> toggleCommentLike(
    String commentId,
    String userId,
  ) async {
    if (!SupabaseClientProvider.isInitialized) {
      return Result.failure(const Failure('Supabase not initialized'));
    }

    try {
      final client = SupabaseClientProvider.client!;

      final existingLike = await client
          .from('comment_likes')
          .select()
          .eq('comment_id', commentId)
          .eq('user_id', userId)
          .maybeSingle();

      if (existingLike != null) {
        await client
            .from('comment_likes')
            .delete()
            .eq('comment_id', commentId)
            .eq('user_id', userId);

        return Result.success(const LikeToggleResult(isLiked: false, likes: 0));
      }

      await client.from('comment_likes').insert({
        'comment_id': commentId,
        'user_id': userId,
      });

      return Result.success(const LikeToggleResult(isLiked: true, likes: 1));
    } catch (e, stack) {
      _logError('toggleCommentLike', e, stack);
      return Result.failure(backendFailure(e, stack));
    }
  }

  // ──────────────────────────────────────────────────────────────
  // Image Upload
  // ──────────────────────────────────────────────────────────────

  /// Uploads an image to the Supabase Storage `posts` bucket and
  /// returns the public URL.
  @override
  Future<Result<String>> uploadImage(String userId, String filePath) async {
    const bucketName = 'posts';

    if (!SupabaseClientProvider.isInitialized) {
      Logger.error('Supabase not initialized.', tag: 'PostRepository');
      return Result.failure(const Failure('Supabase not initialized'));
    }

    try {
      final client = SupabaseClientProvider.client!;
      final authUser = client.auth.currentUser;

      Logger.info(
        '========== STORAGE DEBUG ==========\n'
        'Authenticated User: ${authUser?.id}\n'
        'Method userId: $userId\n'
        'Bucket: $bucketName\n'
        'File: $filePath',
        tag: 'PostRepository',
      );

      if (authUser == null) {
        return Result.failure(const Failure('No authenticated user found.'));
      }

      final file = File(filePath);

      if (!await file.exists()) {
        return Result.failure(Failure('Image file not found: $filePath'));
      }

      final bytes = await file.readAsBytes();
      final ext = file.path.split('.').last.toLowerCase();
      final storagePath =
          '${authUser.id}/${DateTime.now().millisecondsSinceEpoch}.$ext';

      Logger.info('Uploading to: $storagePath', tag: 'PostRepository');

      await client.storage
          .from(bucketName)
          .uploadBinary(
            storagePath,
            bytes,
            fileOptions: FileOptions(
              upsert: false,
              contentType: ext == 'png'
                  ? 'image/png'
                  : ext == 'webp'
                  ? 'image/webp'
                  : 'image/jpeg',
            ),
          );

      Logger.info('Upload successful.', tag: 'PostRepository');

      final publicUrl = client.storage
          .from(bucketName)
          .getPublicUrl(storagePath);

      Logger.info('Public URL: $publicUrl', tag: 'PostRepository');

      return Result.success(publicUrl);
    } on StorageException catch (e, stack) {
      _logError('uploadImage (StorageException)', e, stack);
      return Result.failure(Failure(e.message, error: e, stackTrace: stack));
    } catch (e, stack) {
      _logError('uploadImage (Unknown)', e, stack);
      return Result.failure(Failure(e.toString(), error: e, stackTrace: stack));
    }
  }

  // ──────────────────────────────────────────────────────────────
  // Mapping helpers
  // ──────────────────────────────────────────────────────────────

  /// Maps a Supabase row (with joined profile) to a [Post].
  ///
  /// [fallback] provides default values for fields that may be missing
  /// from the row (e.g. when the profile join returns null).
  Post _mapPostFromRow(Map<String, dynamic> row, Post fallback) {
    final profile = row['profiles'] as Map<String, dynamic>?;

    return Post(
      id: row['id'] as String,
      userId: row['user_id'] as String,
      username: profile?['username'] as String? ?? fallback.username,
      displayName: profile?['display_name'] as String?,
      avatarUrl: profile?['avatar'] as String?,
      content: row['content'] as String? ?? fallback.content,
      mediaUrls: row['media_urls'] != null
          ? List<String>.from(row['media_urls'] as List)
          : fallback.mediaUrls,
      likes: row['likes_count'] as int? ?? fallback.likes,
      comments: row['comments_count'] as int? ?? fallback.comments,
      shares: row['shares_count'] as int? ?? fallback.shares,
      createdAt:
          DateTime.tryParse(row['created_at'] as String? ?? '') ??
          fallback.createdAt,
      updatedAt: row['updated_at'] != null
          ? DateTime.tryParse(row['updated_at'] as String? ?? '')
          : null,
    );
  }

  /// Maps a Supabase row (with joined profile) to a [Comment].
  ///
  /// [fallback] provides default values for fields that may be missing
  /// from the row. When [fallback] is `null` (e.g. when loading a list
  /// of comments), sensible defaults are used.
  Comment _mapCommentFromRow(Map<String, dynamic> row, Comment? fallback) {
    final profile = row['profiles'] as Map<String, dynamic>?;

    return Comment(
      id: row['id'] as String,
      postId: row['post_id'] as String,
      userId: row['user_id'] as String,
      parentId: row['parent_id'] as String?,
      content: row['content'] as String? ?? fallback?.content ?? '',
      username: profile?['username'] as String? ?? fallback?.username ?? 'user',
      displayName: profile?['display_name'] as String?,
      avatarUrl: profile?['avatar'] as String?,
      likesCount: row['likes_count'] as int? ?? 0,
      isEdited: row['is_edited'] as bool? ?? false,
      isDeleted: row['is_deleted'] as bool? ?? false,
      createdAt:
          DateTime.tryParse(row['created_at'] as String? ?? '') ??
          fallback?.createdAt ??
          DateTime.now(),
      updatedAt: row['updated_at'] != null
          ? DateTime.tryParse(row['updated_at'] as String? ?? '')
          : null,
    );
  }

  // ──────────────────────────────────────────────────────────────
  // Debug logging helper (temporary)
  // ──────────────────────────────────────────────────────────────

  /// Logs detailed error information for debugging.
  ///
  /// Logs:
  /// - the exception
  /// - runtime type
  /// - full stack trace
  /// - if [PostgrestException]: code, message, details, hint
  void _logError(String operation, Object e, StackTrace stack) {
    logBackendError(operation, e, stack, tag: 'PostRepository');
  }
}
